const fs = require("fs");

// TODO:
// Need to make sure to pick right level (blue basic, blue, blue extra)
// when appending to cpp on the 'From ____'
// Grab which seat type it is from intercepted points, grab associated cash, create cpp

// HOW TO DO IT:

// 1. Intercept points request, store response in var
// 2. Simulate cash request, store response in var
// 3. Query selector all boxes with points
// 4. If all boxes are loaded in, and assuming all points and cash responses in order:
// -. For each web element, reference corresponding object in array
// 5. Match points in box to that where id = 1
// 6. Take CPP, append to web element
// 7. Move on!

// Regardless, create cpp for all drop down (LATER)

// -------------------------------------------------------------------------------------------------

async function getCash() {
  /**
   * SIMULATE CASH REQUEST
   */

  //   const cash = await fetch("https://jbrest.jetblue.com/lfs-rwb/outboundLFS", {
  //     headers: {
  //       accept: "application/json",
  //       "api-version": "v3",
  //       "application-channel": "Desktop_Web",
  //       "booking-application-type": "NGB",
  //       "content-type": "application/json",
  //       "sec-ch-ua":
  //         '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"',
  //       "sec-ch-ua-mobile": "?0",
  //       "sec-ch-ua-platform": '"Windows"',
  //       "x-1itxwo9i-a":
  //         "mhnDce_evDKdRelwv7190eFaM_R7usrKsLMh0wDUIuFQKcf5XcHWjsExBNdmfN6vKL_8TR1PSigsTGk0agbfYeks2piNzeJ5kZLEfbxWbMUvvtFfsp7eenA6003j=uAzzDjKi_X4dvewCeAkaPq-GjY11=RQG6dFLD74xIJtdYqBCBQr6f4wuHMxMNJisccdEpFFbdqHCL1_G_l7Jy_D747PR4RNQWANWukdaKnMPHubMEnMCgsXIW3IOzD0PMyELr58v3y2wh8pMdUc1Y_2rz12Oe-y5fkplHLR7DUYNOFabh8P_YZYZsG_ki6ID2POWDqLqWnBC8bD-=r3R1xysysJDzHIW9KFOjv8NP-ig8kklSr1wRlYsLcOgdX1WLwlGzXL=3xowleJI35QlXq8nRBZ=0bvoIkRikx15PUtJD=Fvb1PydcNqKY60lwS3Tt5Ipy6eWuxLYEjr-mqpDeuew1n7A=GlJbsv2vHIjLg4KvWh1n13lTgr0Znkd7A-21pou2AP-muQdzI=NAAyi1ECN0gIt=uUiz0vSSRB46pB6SibbENDZ9Fvnc3-wFrEHyO8yCuCs1abDeQ-9RrcpimAH_CKl-BpKez9jzJ-NmlKcErZwGyGd_tGSpUhdJY3tnqtJmt0N9A4J_O4r6IY-_x4UuNp2gGNUC46RkDMjGpTJsf2wSe4UiZ_iHS0X7m8hykatHGDJOJ7dxLc=__LrzH1RMUEaUXfhjLaHTMsdwmUSOkZOzp1peoi_BleDv1Sb5RnsYB0FPawfdxXlACc83W7O-RX1HQUX9gfXBlgffn6u5X5d3-Uy5yiE2Up3ZC93vNkzZeDikyn5=xi=MkIY4AFtdv00FzCPuam=wPotmzkHdnwnGFoNzRaUowqU2lRDqi27RSrRObaO6U8r4vNjI30UcIz=6ow-l5k3dHG5B-XxvaAn3d7X83z0CSbUFYFJbKSw0ku-Tj40Gluao9TSK3F_B3_1XGdE6hneAsNys=9kNOm=mJSvXz3=k8KCqG7au2FjjYUuaj-OCcThm9r=jW0sW9zGz4OXHBZcUEys6NxN_xOFkhqzeGOhFt1vaXNrZPsjmXpEh-gK60s3=G-gkOHfzWhoJTJtWgBWZjK6IRys=zqRUDN6qEtt=9EUT_PID-icpLhLq8iZZ3NWo0SDHQbfLLHm-pH_HnsGuq6fo6jalWrbcgBzSfjvKRM5UTUi2ho-XjH64XeDJ76wtHDEZw_Lc9vOBduszZ-B1QG6vz0F3HUKnq=X8tiQLZwX9zz=gygDv6vh-RUctzrb6JAEjqO-XMZ3pnfO2MYd1KL66o=HmLKM8PjXUYpRQwpSd3IfzXHSjlqtTilmAj_EA4E=lGjsdjT6RXZ7l9vkSx31EiB=RlKopk6682K1mqeSPNwtAHmFPn=Y0IvHRDdT9n41s1XXCJoQqE9i-ceY8AI8A0_LpYWqMTLTDX3-X=QqDZrcveSh-Wmoq3s3m33FXosZdSgvPLZCbAimD_KmCUYAelL9S9FppT_AKiUPfxjQRZesRkIyq6AR_kl6gB1ZDNuxAceds0Uw-Nqv_NUcJZK1SJbZie81ADuAM2zL6cK2MAjxOb-t12eJ-w8cQuut35swFxbsvfZA=XCfFPQ6OaS=qpctBFsd2E5tRq3EY8hc2y-9syf8i8pIbK4a5FY8rP9HM9AnYOSL6la_WtXuSuvQIKBcXr=eDrAtsYaHknyF0IkPbSsdAqaYvTOe2Z0BssvLMlH0rgxcpcAFRsq5L5qIx7eNbXZt3bJkXqsdqYJKkHHcYMCUg-A7ivt2pDUGHYhCIWGTez3Ndr-gQmr5evNHhfzk69nZCIDElvd_eue0bliqS54=r8wOqjgF7AkbtT6Y=JpAzdSLadWqS24=Jxgz9846O5GE_mYAuJ07_MczW2ENvdzft8ErT6G_R=1j8h=bzI-iDsLC5=76xMYrOa-25Y2gTdktEbitLoL4-KEqLdCDl5Ld6e7eJeB2dBwf65mITrQzIf16-6NSx1ij8WZoWGnGnt8LKmqyPfhZ5=5OwwXc0ACGf2lcM-vZMPRApjEzEuJZEWdqcC=1kA6YxjakO9uSPEPYAPUvgAYTgmnfmo1UUTI-11DE6JL4kkoObM5_IUGcFYbLhafAByxTf=NctIkNldlfS1WaojbA87W39fBmcKkXD6QymGpmmqM2IkUErQb9=UBgfY1ReweHz8yb_z6bQGGACLz0F0anktrhbotOU167rkv6zTTYOXpUoC0k_BBUyXivUb3Z4Og2P2L9dnfSGJkG5NBldYlJIvizlnLbe9tLIp5ZNAnbXuFrt827vExGMvZ1_nusObJYRW4PAUx6Gje1MsSUlA5g39XepFerrobyo4n=uaPRoyuuk45M-ZHB_yowXJ2u60b3Sy_5zpH2YrGLllhDQCQmiQdQDt8jzx-vMZl6ueT_E9mjlxSOcMcKAArALhLGrH4FWejIL4Tg0yrHGj70CPYIkOLcUlpfC5pEg0zKCrZ81g-r8RmtNuRtE9N70TDHlSMgtDioBNtlxB1ykt=EHUShTqJRwHjIZtveUMWFxxPwXjwJuKKjIOiIm0lACiT3g=OjMyv-=JdP26-kUC6Ec6_wNR2eGh9cznC=ibcyDRA35w-aXUSlRKdLQxC8SHU0XOtolxzAyAzry6vjE4ddEZXegPi05W7Nkw6DqGJo590ShN_3lhF0oIyp=pZ-rBEcMKagIyoJaEnGqGnlPt2xX9UWE7AGZEqN7YtYdy-ZyY-TwCzWpEmbR4YLs5MOYT_c7AARr=jrgNU__Jgd1O-dD8skWC0axcIFINB78lTxdySrS9IOARQB6ZaEH0TQh55q4Z-tvWRac85DYC6FQ9H3v=Q2uLp1Xn1xi2W7_0Tp92ksxBzpzSiz0N-uBH8l=jpi0pkHZCSyHHMtxbXjNsnxTA1fLzL0Swa48koQIvCEqEjpmRyv=7B1vzH6vA8PJfoEbPvaGxDlh5TKjQvuTUSdcHEe7E54qchW8aZJ3GCFMIejSsbgglUEE7LSH1jEtwKtA7z0vMsNQl7lfS1B_PR9G-lHXWzpx0cLc2j-mU6ThSrsMiiyjb5vxdl9=zeEMeoe0KL1=8g8lUCNu2ek5CvnXO5Udrs8fXRw24F973eo_TsHyczPZ_wgghZzqPc9hNlBaTYIsXKtu9Zn3ZttoU81KBk36hW3NuQ8=IGAGvBRDRkrfH31BnY2=XKdGsrZ_AgmbW8fHk3iUSM0oSwuN5yEmEU6jUO=0A6LkvKf4BtAG5gtHIczm_j5L8wlUNJr5yCscL5KkM1CSGuqjmJAqxmOvToP-It-2oe9qNy=RCcpkHvX0c-tDyOfpJF_2N7M9SxG6AzXnTkpvG3OuWZ-k9F6KOOfrLjZZFnz6DKXieFvK_rr42r52OEcZjk-D9d5pcOETxnFiMq=zfBFslRJbq1ns2xbqhIauXOIAuHo3yy2z9n5Eip-oz0IX4bw3yxm4U-ZIL7y8G7_SUZkLJjxU9LnnIGgrisAr3N9P79-qlS-I_gb32A1NnDSY_hHskrS9RTqYXdZyJ94phG-1Ad1LW6=oQbJUsBhXJWOorpY8mRMOlElIicNUjYBb-FgfH6b8cOho6rofjU1KfAm3JENUSl87vPwDOKAC=6PvCs-SnGxlLwLSi2-0dpvCfz8eJHNrO8lMlcDPnqCQgfIH9v5n0r6MIZhLuTAYr_63KOgRObidv13G6h_JP1HNgE=zo0=on8lW3A4Zna-Rjav0m7M3mXN=mO5EnUrMCSvsu0s6J8auSZQhKtihoDwLFHD8dFyre5UFOiqb5-f65_7hKHc8YAEnEaPxDvc5FubEvNm_AL8XyJSYDE7i2KdZ-ip5de046S8_rxAWS8SnGO-6oAcqmeAg6UgeCZY1f0HSiMWyMNonT3FbI7JTxM-bzsy2NOtmuL9-ZtGAIclu61lgbiOTmoFWBYKcTzHZkhkIyspO17uFaGJUZ-1Z_EWg-DoE4sto_7_cvo1pwRKhIsTYP7JUTA3BDix3YBij8kijFqkUmNnI-UPupO_AmoM42o4XZPMC5U-k6wwPP0LO3f_OcvW7d9LhJ2r0tbasaLZxCnKXtz0xx=k0=roO97ktzEZRDnBQcW-GuDpMMUptGEWdAqjjAAh39yobEY43Fwxl6ip1NyQPuXDSvggkJymlEfHyTyaq=PkCp0FjGAlP_lY3poQbS09d4eQm50CoxQo747CuQF-GI-ur7tWj9K4Hk-LtvPubdXudpsuR65EproaLnrKotns6Jf0QkBmcsgxZ3j_gE7z5P8=0-UZgvCYqfB87dKO-Whu7Zk3ofQhSYkzyRjjToaIzpPUrycMGjwW-rLhOi9BI84O1m=oI552Bow=IHCt47pnzvJQcEOviHdE1Tz410syRoPauM4GWiKK4sCs5N9fhWH0L-68=t3AAbnR0PydDCz_P_2ZHXgWwoDn8kY6J5te3FXy5U8hcuaq9XiTtKpK3Ubh8FQrHXiZ5xHvqZ8HBZwpclEtiI0_rkj2Br2DK=4vNOyBTJclrNApwJSoc7YrsS17xCThW0O-etL6G81APkiWBPrGExWwpkp923ALzwnFvx9uiu5iLUy8tK8MDMzZUwPy9bYGSmkIo6XLIsyKOiqSnalLv3xhgmoxbZWHt30nkjkAj077RP5EgYxGRy1HymhFIujKDyBtskkHHgRhFnI8HnKutF_IzREq9P6OlUwcQYpu04Gx1oX1Onyh4qfQno_Cgo=U_CwIOf6xdLAgaJy4_WQPuwAYn45Y9qsPDkLYJdKBOIRU-cQM_qUnEBxIL2W2vn9edZe5UfOT2jMf4H03vMi6x8UorEOFcNZdR=YM7whRHd8EKkl3JE_IFGzAIZKmSZ43KHUJbdmNHzATfqRtidjpkTObGqIAAlgIdpUyU7zJA3Sywmvx81jHpIYdCPU7IPsRFfI02EJZxmWEPQfnRtSzhk-NasPvh3=C=yQ8XiX7_tc5oah8HB32hEUr-HMS5Tysv-WhgFncJiqg4=m3g6ud8tgio_O2yBMsRcq9n1APuPU9ICpqCS=T4n5C=LyhK_HckHiBXpnHDWUvODnG2IgX=HmYruW4y2mRuR=Nx-yJHT4TWnqWb_MA-EwEbK=TGofQqH1fKI=Kq1xH=eYP2P3z7yX02aPRLhJ8iGv1g7LNYNWp0t78swZkmgMgJ3XL025TG1YKfEK4Ri9uKFh4-rWqX7emnb_jkeQwRyv2cGLPKvTWq0eqDzScP_i3faTMm1LDhPxhDADXUaNX4xuIImpzrUmXNN68OfBQ7rpDg2foRMNPeCX5x2-cyUQOHjz6fQ_c88EGWlWaivnLBPvbifoNko2KDifMAComYC0HN1hlEnQZbxuBoYh=m5YtlTzPZWiRvJCy9qFWrPvAc1i2pJpaeaGXAXWRAbk3xAcMCL2fknI_-LSd3yvHFi-OiAJQE49RorlS7BcEgkglM-cLJadxFeu-IqhQh_4dGPHkTnISc=YF8H5gsmRqhJoyYx_mBJdiaAFHs1gLfKxbtgdhy0EJOh=CnZNeHyANXzZC-WJELAw30mMUPKxPCPbOLKpqCiUDsM2OUeuj8xUQxDv=ftLbdWmFx8bo2C5oBd0y4jXy8HheDtT43h_2pywcDl5iBc2lPX82G53XHLcrgc_Pxtzvtg6gZivkY3LIZEmlQyTtsvOsMokRxsiKcftppP_p6JG_2KDIW64x0OaNOG85wdBe6rI34_oZc3L2W09wfG-vx4DWbABBN7lc=Ynx==bqSBz=Y0iav_HTRneTahoo9NY8wCUKXRKvF=8mE7GTsKC9UXF=TXSZojPIKCD0Igh-HY8oK-2qrJC9bmSNwDF2TeUKkGYZwTuln-0322-WmGXmdLSCc2dPIrmBfHDaNvZsm4DuCAl-522q8rJG3R8Qmyr1aAF8tNfhGZIwgttD7AKxUNM=Gur80Xix7s6ZS88F=raCKzcsUc7vaod-djA_=tzMpKQw=E2ybXXGakoyK3wNhmIj2A_XZePkrU_x8FxZ-si3XmNA_0xuyHfhFDzudaCtBdzZ2l5veUFN2q6PgTkJ_lK_Y00w-5OSUKeYv0iGO2sJXNSf3LbpN5LRDkXI5h_7IfH-6xpaIKNCzYZTsc71D4jeupE9TJD-FSopj1Lknfx9yCIv4pChZUrX0NP-7l0A-UlmXw0=n5lcJGgtt9IjBHRK9y-mIShDESlqy6WTHGg5aWpXt2n2wq5uSdaSBDvn5xTC1USYszMqkJEqd7aoSqtph6jsfWX_Xkynl_AYTucbLMb9G-92oGuBY2Ita74CSE8ocOBy=96rDkA5b3TP_eBFT=xC8upGkxgO1cXXpcHXirSO274AdU3ZLTbBqz8XDMGSw1RfEcib-Xc_5nxK9xPSmFWnCcupgEOZSemtje5j_n7it2M5a4Qb5qSQuUE5=Po8G0-0vUBeIOs2b8D6QZQ253jDOCRX5l6Av6aPqGmM30z4Se27N_cSUJzX-5NCi4gazMD21EsvZtJins=sZAKhrBo7yjAh5ES8NGlbHbGiAfgSCbCB945Ow4HgOMYkGXsDW9XOKduKhZF1OdhSO5O6g=wW2qRfajgrfrnAmXysS9TiTyzcS=hfohSql=M9IbUXLRnfHcb8JMiERE",
  //       "x-1itxwo9i-b": "-kukwcf",
  //       "x-1itxwo9i-c":
  //         "AKDVXeqLAQAAwRKzfDmmxB44r6ASoM3hUvVknWM_hpNzNXC96GPAld57wsf6",
  //       "x-1itxwo9i-d":
  //         "ABaAhIDBCKGFgQGAAYIQgISigaIAwBGAzvpCzi_33wdjwJXee8LH-gAAAAByzJzLAMccBGMediKBbiY3VweObxQ",
  //       "x-1itxwo9i-f":
  //         "A2CYYeqLAQAAJys6B8DqSP8z_h2hFXWid_Aw9jCozD0pl5GU6pxM5qCguuMVAUkmEOGuciGywH8AAEB3AAAAAA==",
  //       "x-1itxwo9i-z": "q",
  //       "x-auth-token": "a3134b4c-07f9-48eb-9da4-167223f03bfd",
  //       "x-b3-spanid": "1700444463721",
  //       "x-b3-traceid": "9b1435a63b682fda",
  //     },
  //     referrer:
  //       "https://www.jetblue.com/booking/flights?from=JFK&to=TPA&depart=2023-12-14&isMultiCity=false&noOfRoute=1&lang=en&adults=1&children=0&infants=0&sharedMarket=false&roundTripFaresFlag=false&usePoints=true",
  //     referrerPolicy: "no-referrer-when-downgrade",
  //     body: '{"tripType":"oneWay","from":"JFK","to":"TPA","depart":"2023-12-14","cabin":"economy","refundable":false,"dates":{"before":"3","after":"3"},"pax":{"ADT":1,"CHD":0,"INF":0,"UNN":0},"redempoint":false,"pointsBreakup":{"option":"","value":0},"isMultiCity":false,"isDomestic":false}',
  //     method: "POST",
  //     mode: "cors",
  //     credentials: "omit",
  //   })
  //     .then((response) => response.text())
  //     .catch((error) => console.log("error", error));

  const cash = {
    dategroup: [
      {
        to: "TPA",
        from: "JFK",
        group: [
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-11",
            date: "2023-12-11T00:00:00-05:00",
            price: "68.90",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-12",
            date: "2023-12-12T00:00:00-05:00",
            price: "68.90",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-13",
            date: "2023-12-13T00:00:00-05:00",
            price: "68.90",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-14",
            date: "2023-12-14T00:00:00-05:00",
            price: "78.89",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-15",
            date: "2023-12-15T00:00:00-05:00",
            price: "78.89",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-16",
            date: "2023-12-16T00:00:00-05:00",
            price: "78.89",
          },
          {
            uri: "/air/lfs/655ac97618ce732ac8c30bab/origins-destinations/1/departure-dates/2023-12-17",
            date: "2023-12-17T00:00:00-05:00",
            price: "78.89",
          },
        ],
      },
    ],
    itinerary: [
      {
        id: "1",
        sequenceID: "1",
        from: "JFK",
        to: "TPA",
        depart: "2023-12-14T10:30:00-05:00",
        arrive: "2023-12-14T13:36:00-05:00",
        isOverNightFlight: false,
        isQuickest: true,
        duration: "PT3H6M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/1_1",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "78.89",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/1_2",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "103.90",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/1_3",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "128.90",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/1_4",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "161.70",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/1_5",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "191.71",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_2725_2023-12-14_JFK_TPA",
            from: "JFK",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_TPA",
            stops: 0,
            depart: "2023-12-14T10:30:00-05:00",
            arrive: "2023-12-14T13:36:00-05:00",
            flightno: "2725",
            duration: "PT3H6M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/1/flight-segments/B6_2725_2023-12-14_JFK_TPA:32M",
            distance: 1005,
            operatingFlightno: "2725",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "TPA",
                departureTerminal: "5",
                duration: "PT3H6M",
              },
            ],
          },
        ],
      },
      {
        id: "2",
        sequenceID: "2",
        from: "JFK",
        to: "TPA",
        depart: "2023-12-14T13:00:00-05:00",
        arrive: "2023-12-14T16:07:00-05:00",
        isOverNightFlight: false,
        isQuickest: true,
        duration: "PT3H7M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/2_6",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "78.89",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/2_7",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "103.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/2_8",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "128.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/2_9",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "161.70",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/2_10",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "191.71",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_125_2023-12-14_JFK_TPA",
            from: "JFK",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_TPA",
            stops: 0,
            depart: "2023-12-14T13:00:00-05:00",
            arrive: "2023-12-14T16:07:00-05:00",
            flightno: "125",
            duration: "PT3H7M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/2/flight-segments/B6_125_2023-12-14_JFK_TPA:32M",
            distance: 1005,
            operatingFlightno: "125",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "TPA",
                departureTerminal: "5",
                duration: "PT3H7M",
              },
            ],
          },
        ],
      },
      {
        id: "3",
        sequenceID: "3",
        from: "JFK",
        to: "TPA",
        depart: "2023-12-14T15:59:00-05:00",
        arrive: "2023-12-14T19:05:00-05:00",
        isOverNightFlight: false,
        isQuickest: true,
        duration: "PT3H6M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/3_11",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "78.89",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/3_12",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "103.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/3_13",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "128.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/3_14",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "161.70",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/3_15",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "191.71",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_2825_2023-12-14_JFK_TPA",
            from: "JFK",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_TPA",
            stops: 0,
            depart: "2023-12-14T15:59:00-05:00",
            arrive: "2023-12-14T19:05:00-05:00",
            flightno: "2825",
            duration: "PT3H6M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/3/flight-segments/B6_2825_2023-12-14_JFK_TPA:32M",
            distance: 1005,
            operatingFlightno: "2825",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "TPA",
                departureTerminal: "5",
                duration: "PT3H6M",
              },
            ],
          },
        ],
      },
      {
        id: "4",
        sequenceID: "4",
        from: "JFK",
        to: "TPA",
        depart: "2023-12-14T18:00:00-05:00",
        arrive: "2023-12-14T21:09:00-05:00",
        isOverNightFlight: false,
        isQuickest: true,
        duration: "PT3H9M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/4_16",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "78.89",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/4_17",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "103.90",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/4_18",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "128.90",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/4_19",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "161.70",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/4_20",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "191.71",
            cabinclass: "Y",
            bookingclass: "S",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_2325_2023-12-14_JFK_TPA",
            from: "JFK",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_TPA",
            stops: 0,
            depart: "2023-12-14T18:00:00-05:00",
            arrive: "2023-12-14T21:09:00-05:00",
            flightno: "2325",
            duration: "PT3H9M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/4/flight-segments/B6_2325_2023-12-14_JFK_TPA:32M",
            distance: 1005,
            operatingFlightno: "2325",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "TPA",
                departureTerminal: "5",
                duration: "PT3H9M",
              },
            ],
          },
        ],
      },
      {
        id: "5",
        sequenceID: "5",
        from: "JFK",
        to: "TPA",
        depart: "2023-12-14T20:35:00-05:00",
        arrive: "2023-12-14T23:47:00-05:00",
        isOverNightFlight: false,
        isQuickest: true,
        duration: "PT3H12M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/5_21",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "78.89",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/5_22",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "103.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/5_23",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "128.90",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/5_24",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "161.70",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/5_25",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "191.71",
            cabinclass: "Y",
            bookingclass: "S",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_225_2023-12-14_JFK_TPA",
            from: "JFK",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_TPA",
            stops: 0,
            depart: "2023-12-14T20:35:00-05:00",
            arrive: "2023-12-14T23:47:00-05:00",
            flightno: "225",
            duration: "PT3H12M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/5/flight-segments/B6_225_2023-12-14_JFK_TPA:32M",
            distance: 1005,
            operatingFlightno: "225",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "TPA",
                departureTerminal: "5",
                duration: "PT3H12M",
              },
            ],
          },
        ],
      },
      {
        id: "6",
        sequenceID: "6",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T06:00:00-05:00",
        arrive: "2023-12-14T11:40:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT5H40M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/6_26",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "207.20",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/6_27",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "257.20",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/6_28",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "302.21",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/6_29",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "367.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/6_30",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "397.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_318_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "E190",
            aircraftCode: "E90",
            aircraftAmenityKey: "E90_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T06:00:00-05:00",
            arrive: "2023-12-14T07:15:00-05:00",
            flightno: "318",
            duration: "PT1H15M",
            layover: "PT54M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/6/flight-segments/B6_318_2023-12-14_JFK_BOS:E90",
            distance: 187,
            operatingFlightno: "318",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H15M",
              },
            ],
          },
          {
            id: "B6_591_2023-12-14_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "A321",
            aircraftCode: "321",
            aircraftAmenityKey: "321_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-14T08:09:00-05:00",
            arrive: "2023-12-14T11:40:00-05:00",
            flightno: "591",
            duration: "PT3H31M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/6/flight-segments/B6_591_2023-12-14_BOS_TPA:321",
            distance: 1185,
            operatingFlightno: "591",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H31M",
              },
            ],
          },
        ],
      },
      {
        id: "7",
        sequenceID: "7",
        from: "JFK",
        to: "TPA",
        connections: ["FLL"],
        depart: "2023-12-14T07:14:00-05:00",
        arrive: "2023-12-14T17:25:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT10H11M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/7_31",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "226.80",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_601_2023-12-14_JFK_FLL",
            from: "JFK",
            to: "FLL",
            aircraft: "A321",
            aircraftCode: "3N1",
            aircraftAmenityKey: "3N1_B6_FLL_JFK",
            stops: 0,
            depart: "2023-12-14T07:14:00-05:00",
            arrive: "2023-12-14T10:24:00-05:00",
            flightno: "601",
            duration: "PT3H10M",
            layover: "PT5H46M",
            bookingclass: "P",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/7/flight-segments/B6_601_2023-12-14_JFK_FLL:3N1",
            distance: 1069,
            operatingFlightno: "601",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "FLL",
                departureTerminal: "5",
                arrivalTerminal: "3",
                duration: "PT3H10M",
              },
            ],
          },
          {
            id: "B6_5492_2023-12-14_FLL_TPA",
            from: "FLL",
            to: "TPA",
            aircraft: "ATR 42 Turboprop",
            aircraftCode: "AT4",
            aircraftAmenityKey: "AT4_3M_FLL_TPA",
            stops: 0,
            depart: "2023-12-14T16:10:00-05:00",
            arrive: "2023-12-14T17:25:00-05:00",
            flightno: "5492",
            duration: "PT1H15M",
            bookingclass: "W",
            cabinclass: "Y",
            operatingAirlineCode: "3M",
            marketingAirlineCode: "B6",
            operatingAirlineName: "Silver Airways",
            marketingAirlineName: "JetBlue",
            filingAirline: "Silver Airways",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/7/flight-segments/B6_5492_2023-12-14_FLL_TPA:AT4",
            distance: 197,
            operatingFlightno: "92",
            throughFlightLegs: [
              {
                departureAirport: "FLL",
                arrivalAirport: "TPA",
                departureTerminal: "1",
                duration: "PT1H15M",
              },
            ],
          },
        ],
      },
      {
        id: "8",
        sequenceID: "8",
        from: "JFK",
        to: "TPA",
        connections: ["FLL"],
        depart: "2023-12-14T09:49:00-05:00",
        arrive: "2023-12-14T20:00:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT10H11M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/8_32",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "222.81",
            cabinclass: "Y",
            bookingclass: "U",
            inventoryQuantity: "3",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_2201_2023-12-14_JFK_FLL",
            from: "JFK",
            to: "FLL",
            aircraft: "A321",
            aircraftCode: "321",
            aircraftAmenityKey: "321_B6_FLL_JFK",
            stops: 0,
            depart: "2023-12-14T09:49:00-05:00",
            arrive: "2023-12-14T13:00:00-05:00",
            flightno: "2201",
            duration: "PT3H11M",
            layover: "PT5H45M",
            bookingclass: "U",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/8/flight-segments/B6_2201_2023-12-14_JFK_FLL:321",
            distance: 1069,
            operatingFlightno: "2201",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "FLL",
                departureTerminal: "5",
                arrivalTerminal: "3",
                duration: "PT3H11M",
              },
            ],
          },
          {
            id: "B6_5454_2023-12-14_FLL_TPA",
            from: "FLL",
            to: "TPA",
            aircraft: "ATR 72 Turboprop",
            aircraftCode: "AT7",
            aircraftAmenityKey: "AT7_3M_FLL_TPA",
            stops: 0,
            depart: "2023-12-14T18:45:00-05:00",
            arrive: "2023-12-14T20:00:00-05:00",
            flightno: "5454",
            duration: "PT1H15M",
            bookingclass: "U",
            cabinclass: "Y",
            operatingAirlineCode: "3M",
            marketingAirlineCode: "B6",
            operatingAirlineName: "Silver Airways",
            marketingAirlineName: "JetBlue",
            filingAirline: "Silver Airways",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/8/flight-segments/B6_5454_2023-12-14_FLL_TPA:AT7",
            distance: 197,
            operatingFlightno: "54",
            throughFlightLegs: [
              {
                departureAirport: "FLL",
                arrivalAirport: "TPA",
                departureTerminal: "1",
                duration: "PT1H15M",
              },
            ],
          },
        ],
      },
      {
        id: "9",
        sequenceID: "9",
        from: "JFK",
        to: "TPA",
        connections: ["FLL"],
        depart: "2023-12-14T09:49:00-05:00",
        arrive: "2023-12-14T17:25:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT7H36M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/9_33",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "256.21",
            cabinclass: "Y",
            bookingclass: "U",
            inventoryQuantity: "3",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_2201_2023-12-14_JFK_FLL",
            from: "JFK",
            to: "FLL",
            aircraft: "A321",
            aircraftCode: "321",
            aircraftAmenityKey: "321_B6_FLL_JFK",
            stops: 0,
            depart: "2023-12-14T09:49:00-05:00",
            arrive: "2023-12-14T13:00:00-05:00",
            flightno: "2201",
            duration: "PT3H11M",
            layover: "PT3H10M",
            bookingclass: "U",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/9/flight-segments/B6_2201_2023-12-14_JFK_FLL:321",
            distance: 1069,
            operatingFlightno: "2201",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "FLL",
                departureTerminal: "5",
                arrivalTerminal: "3",
                duration: "PT3H11M",
              },
            ],
          },
          {
            id: "B6_5492_2023-12-14_FLL_TPA",
            from: "FLL",
            to: "TPA",
            aircraft: "ATR 42 Turboprop",
            aircraftCode: "AT4",
            aircraftAmenityKey: "AT4_3M_FLL_TPA",
            stops: 0,
            depart: "2023-12-14T16:10:00-05:00",
            arrive: "2023-12-14T17:25:00-05:00",
            flightno: "5492",
            duration: "PT1H15M",
            bookingclass: "W",
            cabinclass: "Y",
            operatingAirlineCode: "3M",
            marketingAirlineCode: "B6",
            operatingAirlineName: "Silver Airways",
            marketingAirlineName: "JetBlue",
            filingAirline: "Silver Airways",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/9/flight-segments/B6_5492_2023-12-14_FLL_TPA:AT4",
            distance: 197,
            operatingFlightno: "92",
            throughFlightLegs: [
              {
                departureAirport: "FLL",
                arrivalAirport: "TPA",
                departureTerminal: "1",
                duration: "PT1H15M",
              },
            ],
          },
        ],
      },
      {
        id: "10",
        sequenceID: "10",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T10:30:00-05:00",
        arrive: "2023-12-14T19:40:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT9H10M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/10_34",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "182.80",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/10_35",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "232.79",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/10_36",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "261.81",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/10_37",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "318.21",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/10_38",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "348.20",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_218_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T10:30:00-05:00",
            arrive: "2023-12-14T11:48:00-05:00",
            flightno: "218",
            duration: "PT1H18M",
            layover: "PT4H24M",
            bookingclass: "O",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/10/flight-segments/B6_218_2023-12-14_JFK_BOS:32M",
            distance: 187,
            operatingFlightno: "218",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H18M",
              },
            ],
          },
          {
            id: "B6_1191_2023-12-14_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "A321",
            aircraftCode: "321",
            aircraftAmenityKey: "321_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-14T16:12:00-05:00",
            arrive: "2023-12-14T19:40:00-05:00",
            flightno: "1191",
            duration: "PT3H28M",
            bookingclass: "O",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/10/flight-segments/B6_1191_2023-12-14_BOS_TPA:321",
            distance: 1185,
            operatingFlightno: "1191",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H28M",
              },
            ],
          },
        ],
      },
      {
        id: "11",
        sequenceID: "11",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T10:30:00-05:00",
        arrive: "2023-12-14T18:10:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT7H40M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/11_39",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "207.20",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/11_40",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "257.20",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/11_41",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "302.21",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/11_42",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "367.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/11_43",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "397.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_218_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T10:30:00-05:00",
            arrive: "2023-12-14T11:48:00-05:00",
            flightno: "218",
            duration: "PT1H18M",
            layover: "PT2H57M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/11/flight-segments/B6_218_2023-12-14_JFK_BOS:32M",
            distance: 187,
            operatingFlightno: "218",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H18M",
              },
            ],
          },
          {
            id: "B6_1291_2023-12-14_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "E190",
            aircraftCode: "E90",
            aircraftAmenityKey: "E90_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-14T14:45:00-05:00",
            arrive: "2023-12-14T18:10:00-05:00",
            flightno: "1291",
            duration: "PT3H25M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/11/flight-segments/B6_1291_2023-12-14_BOS_TPA:E90",
            distance: 1185,
            operatingFlightno: "1291",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H25M",
              },
            ],
          },
        ],
      },
      {
        id: "12",
        sequenceID: "12",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T12:37:00-05:00",
        arrive: "2023-12-14T19:40:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT7H3M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/12_44",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "177.20",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/12_45",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "227.19",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/12_46",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "256.21",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/12_47",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "312.61",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/12_48",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "342.60",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "1",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_1518_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "A220",
            aircraftCode: "223",
            aircraftAmenityKey: "223_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T12:37:00-05:00",
            arrive: "2023-12-14T13:55:00-05:00",
            flightno: "1518",
            duration: "PT1H18M",
            layover: "PT2H17M",
            bookingclass: "O",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/12/flight-segments/B6_1518_2023-12-14_JFK_BOS:223",
            distance: 187,
            operatingFlightno: "1518",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H18M",
              },
            ],
          },
          {
            id: "B6_1191_2023-12-14_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "A321",
            aircraftCode: "321",
            aircraftAmenityKey: "321_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-14T16:12:00-05:00",
            arrive: "2023-12-14T19:40:00-05:00",
            flightno: "1191",
            duration: "PT3H28M",
            bookingclass: "O",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/12/flight-segments/B6_1191_2023-12-14_BOS_TPA:321",
            distance: 1185,
            operatingFlightno: "1191",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H28M",
              },
            ],
          },
        ],
      },
      {
        id: "13",
        sequenceID: "13",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T12:37:00-05:00",
        arrive: "2023-12-14T18:10:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT5H33M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/13_49",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "207.20",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/13_50",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "257.20",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/13_51",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "302.21",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/13_52",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "367.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/13_53",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "397.81",
            cabinclass: "Y",
            bookingclass: "Z",
            inventoryQuantity: "5",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_1518_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "A220",
            aircraftCode: "223",
            aircraftAmenityKey: "223_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T12:37:00-05:00",
            arrive: "2023-12-14T13:55:00-05:00",
            flightno: "1518",
            duration: "PT1H18M",
            layover: "PT50M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/13/flight-segments/B6_1518_2023-12-14_JFK_BOS:223",
            distance: 187,
            operatingFlightno: "1518",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H18M",
              },
            ],
          },
          {
            id: "B6_1291_2023-12-14_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "E190",
            aircraftCode: "E90",
            aircraftAmenityKey: "E90_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-14T14:45:00-05:00",
            arrive: "2023-12-14T18:10:00-05:00",
            flightno: "1291",
            duration: "PT3H25M",
            bookingclass: "Z",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/13/flight-segments/B6_1291_2023-12-14_BOS_TPA:E90",
            distance: 1185,
            operatingFlightno: "1291",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H25M",
              },
            ],
          },
        ],
      },
      {
        id: "14",
        sequenceID: "14",
        from: "JFK",
        to: "TPA",
        connections: ["FLL"],
        depart: "2023-12-14T13:05:00-05:00",
        arrive: "2023-12-14T20:00:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT6H55M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/14_54",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "232.20",
            cabinclass: "Y",
            bookingclass: "O",
            inventoryQuantity: "4",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_1401_2023-12-14_JFK_FLL",
            from: "JFK",
            to: "FLL",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_FLL_JFK",
            stops: 0,
            depart: "2023-12-14T13:05:00-05:00",
            arrive: "2023-12-14T16:16:00-05:00",
            flightno: "1401",
            duration: "PT3H11M",
            layover: "PT2H29M",
            bookingclass: "O",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/14/flight-segments/B6_1401_2023-12-14_JFK_FLL:32M",
            distance: 1069,
            operatingFlightno: "1401",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "FLL",
                departureTerminal: "5",
                arrivalTerminal: "3",
                duration: "PT3H11M",
              },
            ],
          },
          {
            id: "B6_5454_2023-12-14_FLL_TPA",
            from: "FLL",
            to: "TPA",
            aircraft: "ATR 72 Turboprop",
            aircraftCode: "AT7",
            aircraftAmenityKey: "AT7_3M_FLL_TPA",
            stops: 0,
            depart: "2023-12-14T18:45:00-05:00",
            arrive: "2023-12-14T20:00:00-05:00",
            flightno: "5454",
            duration: "PT1H15M",
            bookingclass: "U",
            cabinclass: "Y",
            operatingAirlineCode: "3M",
            marketingAirlineCode: "B6",
            operatingAirlineName: "Silver Airways",
            marketingAirlineName: "JetBlue",
            filingAirline: "Silver Airways",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/14/flight-segments/B6_5454_2023-12-14_FLL_TPA:AT7",
            distance: 197,
            operatingFlightno: "54",
            throughFlightLegs: [
              {
                departureAirport: "FLL",
                arrivalAirport: "TPA",
                departureTerminal: "1",
                duration: "PT1H15M",
              },
            ],
          },
        ],
      },
      {
        id: "15",
        sequenceID: "15",
        from: "JFK",
        to: "TPA",
        connections: ["SJU"],
        depart: "2023-12-14T14:05:00-05:00",
        arrive: "2023-12-14T23:34:00-05:00",
        isOverNightFlight: false,
        isQuickest: false,
        duration: "PT9H29M",
        arrivalOffset: "0",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/15_55",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "340.80",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/15_56",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "395.80",
            cabinclass: "Y",
            bookingclass: "M",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/15_57",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "445.80",
            cabinclass: "Y",
            bookingclass: "M",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/15_58",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "538.02",
            cabinclass: "Y",
            bookingclass: "M",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/15_59",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "598.02",
            cabinclass: "Y",
            bookingclass: "M",
            status: "AVAILABLE",
          },
        ],
        segments: [
          {
            id: "B6_803_2023-12-14_JFK_SJU",
            from: "JFK",
            to: "SJU",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_JFK_SJU",
            stops: 0,
            depart: "2023-12-14T14:05:00-05:00",
            arrive: "2023-12-14T19:04:00-04:00",
            flightno: "803",
            duration: "PT3H59M",
            layover: "PT2H16M",
            bookingclass: "M",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/15/flight-segments/B6_803_2023-12-14_JFK_SJU:32M",
            distance: 1597,
            operatingFlightno: "803",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "SJU",
                departureTerminal: "5",
                arrivalTerminal: "A",
                duration: "PT3H59M",
              },
            ],
          },
          {
            id: "B6_2752_2023-12-14_SJU_TPA",
            from: "SJU",
            to: "TPA",
            aircraft: "A320",
            aircraftCode: "32M",
            aircraftAmenityKey: "32M_B6_SJU_TPA",
            stops: 0,
            depart: "2023-12-14T21:20:00-04:00",
            arrive: "2023-12-14T23:34:00-05:00",
            flightno: "2752",
            duration: "PT3H14M",
            bookingclass: "S",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/15/flight-segments/B6_2752_2023-12-14_SJU_TPA:32M",
            distance: 1237,
            operatingFlightno: "2752",
            throughFlightLegs: [
              {
                departureAirport: "SJU",
                arrivalAirport: "TPA",
                departureTerminal: "A",
                duration: "PT3H14M",
              },
            ],
          },
        ],
      },
      {
        id: "16",
        sequenceID: "16",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T23:45:00-05:00",
        arrive: "2023-12-15T09:29:00-05:00",
        isOverNightFlight: true,
        isQuickest: false,
        duration: "PT9H44M",
        arrivalOffset: "1",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/16_60",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "242.80",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/16_61",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "292.80",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/16_62",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "352.79",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "6cafe39b-8e7b-4978-8cab-efebd94541f2",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "N/A",
            cabinclass: "N/A",
            status: "SOLD_OUT",
          },
          {
            id: "daa0e12a-fbd4-46e3-af16-f2b75ebaa1c4",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "N/A",
            cabinclass: "N/A",
            status: "SOLD_OUT",
          },
        ],
        segments: [
          {
            id: "B6_918_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "E190",
            aircraftCode: "E90",
            aircraftAmenityKey: "E90_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T23:45:00-05:00",
            arrive: "2023-12-15T00:59:00-05:00",
            flightno: "918",
            duration: "PT1H14M",
            layover: "PT5H5M",
            bookingclass: "P",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/16/flight-segments/B6_918_2023-12-14_JFK_BOS:E90",
            distance: 187,
            operatingFlightno: "918",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H14M",
              },
            ],
          },
          {
            id: "B6_891_2023-12-15_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "A220",
            aircraftCode: "223",
            aircraftAmenityKey: "223_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-15T06:04:00-05:00",
            arrive: "2023-12-15T09:29:00-05:00",
            flightno: "891",
            duration: "PT3H25M",
            bookingclass: "M",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/16/flight-segments/B6_891_2023-12-15_BOS_TPA:223",
            distance: 1185,
            operatingFlightno: "891",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H25M",
              },
            ],
          },
        ],
      },
      {
        id: "17",
        sequenceID: "17",
        from: "JFK",
        to: "TPA",
        connections: ["BOS"],
        depart: "2023-12-14T23:45:00-05:00",
        arrive: "2023-12-15T12:09:00-05:00",
        isOverNightFlight: true,
        isQuickest: false,
        duration: "PT12H24M",
        arrivalOffset: "1",
        bundles: [
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/17_63",
            code: "BLUE_BASIC",
            refundable: "false",
            fareCode: "DN",
            price: "242.80",
            cabinclass: "Y",
            bookingclass: "L",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/17_64",
            code: "BLUE",
            refundable: "false",
            fareCode: "AN",
            price: "292.80",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "/air/lfs/655ac97618ce732ac8c30bab/itinerary-prices/17_65",
            code: "BLUE_EXTRA",
            refundable: "false",
            fareCode: "GN",
            price: "352.79",
            cabinclass: "Y",
            bookingclass: "P",
            inventoryQuantity: "2",
            status: "AVAILABLE",
          },
          {
            id: "6c57a273-9cf0-48f7-9a8e-b36763a1dac9",
            code: "BLUE_REFUNDABLE",
            refundable: "true",
            fareCode: "AR",
            price: "N/A",
            cabinclass: "N/A",
            status: "SOLD_OUT",
          },
          {
            id: "ebdfc729-078c-4155-b8b1-e296ffc34718",
            code: "BLUE_EXTRA_REFUNDABLE",
            refundable: "true",
            fareCode: "GR",
            price: "N/A",
            cabinclass: "N/A",
            status: "SOLD_OUT",
          },
        ],
        segments: [
          {
            id: "B6_918_2023-12-14_JFK_BOS",
            from: "JFK",
            to: "BOS",
            aircraft: "E190",
            aircraftCode: "E90",
            aircraftAmenityKey: "E90_B6_BOS_JFK",
            stops: 0,
            depart: "2023-12-14T23:45:00-05:00",
            arrive: "2023-12-15T00:59:00-05:00",
            flightno: "918",
            duration: "PT1H14M",
            layover: "PT7H41M",
            bookingclass: "P",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/17/flight-segments/B6_918_2023-12-14_JFK_BOS:E90",
            distance: 187,
            operatingFlightno: "918",
            throughFlightLegs: [
              {
                departureAirport: "JFK",
                arrivalAirport: "BOS",
                departureTerminal: "5",
                arrivalTerminal: "C",
                duration: "PT1H14M",
              },
            ],
          },
          {
            id: "B6_591_2023-12-15_BOS_TPA",
            from: "BOS",
            to: "TPA",
            aircraft: "A220",
            aircraftCode: "223",
            aircraftAmenityKey: "223_B6_BOS_TPA",
            stops: 0,
            depart: "2023-12-15T08:40:00-05:00",
            arrive: "2023-12-15T12:09:00-05:00",
            flightno: "591",
            duration: "PT3H29M",
            bookingclass: "M",
            cabinclass: "Y",
            operatingAirlineCode: "B6",
            marketingAirlineCode: "B6",
            operatingAirlineName: "JetBlue",
            marketingAirlineName: "JetBlue",
            filingAirline: "JetBlue",
            marketingAirline: "JetBlue",
            seatMapUri:
              "/air/lfs/655ac97618ce732ac8c30bab/itineraries/17/flight-segments/B6_591_2023-12-15_BOS_TPA:223",
            distance: 1185,
            operatingFlightno: "591",
            throughFlightLegs: [
              {
                departureAirport: "BOS",
                arrivalAirport: "TPA",
                departureTerminal: "C",
                duration: "PT3H29M",
              },
            ],
          },
        ],
      },
    ],
    stopsFilter: [0, 1],
    countryCode: "US",
    pos: "JETBLUEMOBILEREVENUE_US",
    currency: "USD",
    programName: "FO2 BASIC",
    isTransatlanticRoute: false,
  };

  // let points = document.querySelectorAll(".pointsText");

  addCppLowestPoints(
    cash,
    //.map(({ code, price }) => ({ code, price })),
    "BLUE_BASIC",
    1
  );

  return cash;
}
getCash();

/**
 *
 * addCppLowestPoints()
 * @param {*} cash the response of the simulated request for cash values of flights using...
 * the parameters chosen in the organic points request (departure airport, arrival port, ...)
 * @param {*} points the response of the organic points request JBLUE website makes...
 * when you search a trip using points
 * @param {*} webElements, where we are to add the 'cpp' data on the page once calculated
 *
 * @returns {*} flights, the array of flight objects created within func
 */
async function addCppLowestPoints(cash, points, webElements) {
  // Create array to store all flight obj in
  const flights = [];

  for (let i = 0; i < cash.itinerary.length; i++) {
    for (let j = 0; j < cash.itinerary[i].bundles.length; j++) {
      let specCash = cash.itinerary[i];

      // CHANGE SPEC CASH TO POINTS LATER
      // Create an object for each flight, with cash value and points value, along with other useful info

      let flight = {
        id: parseInt(specCash.id),
        pathId: specCash.bundles[j].id,
        to: specCash.to,
        from: specCash.from,
        seatCode: specCash.bundles[j].code,
        cash: parseInt(specCash.bundles[j].price),
        points: 999,
        status: specCash.bundles[j].status,
      };

      flights.push(flight);
    } // for j
  } // for i

  // Now that we have an array of objects that contains cash values and points values for every
  // ... flight, we can now loop through the web elements to attach cpp to the front facing singular
  // ... point value. We need to be sure that we pick the right cash value to match up however

  // TEST EXAMPLE
  let index = 13;
  let elmCash = 367;

  // Change to: loop through unique ids in flights var
  for (let k = index; k < 14; k++) {
    let webElement = webElements[k - 1];

    let matchedPoints = flights
      .filter((flight) => flight.id === index) // subset all flights to only 1, with all seat code options
      .filter((flight) => flight.cash === elmCash)[0].cash; // change to match points from web element

    console.log(matchedPoints);

    // Append to web element k - 1
  } // for k

  // We now have the data containing the correct seat code shown on screen and the associated cash

  // Calc CPP

  // APPEND TO WEBELEMENT

  return flights;
} // addCppLowestPoints()

/**
 *
 * Likely will have to be an onclick function
 * When you click on "From ___" points box, able to see all seat codes and associated points
 * Need to match up cash values with appropriate point box
 * @param {*} flights, the array of all flights returned by addCppLowestPoints()
 * @param {*} webElements, the entire array of points boxes on page
 *
 */
async function addCppAllSeatCodes(flights, webElements) {
  // Click on the front facing points
  // Drop down open
  // Can hopefully match up the web element array number and points values to identify correct flight array entry
}

// /**
//  * To be able to append the correct CPP to the web elm, we need to figure out
//  * which points value is being displayed and from which seat type
//  * It is NOT always the lowest seat code
//  * @param {*} points a singular points value that is shown on the front end
//  * @param {*}
//  */
// function matchPointsToSeatCode() {}
